/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salvataggionatale;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author lleshi.alessandro
 */
public class SalvataggioNataleInterface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SalvataggioNataleInterface.class.getName());
    
    Elfo e;
    Macchinario m;
    Giocattolo g;
    
    
    
    public SalvataggioNataleInterface() {
        Color c = new Color(30,160,30);
        this.getContentPane().setBackground(c);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scegliElfo1 = new javax.swing.JComboBox<>();
        scegliElfo = new javax.swing.JComboBox<>();
        scegliMacchinario = new javax.swing.JComboBox<>();
        assegnaElfo = new javax.swing.JButton();
        assegnaMacchinario = new javax.swing.JButton();
        materialiComboBox = new javax.swing.JComboBox<>();
        nomeGiocattolo = new javax.swing.JLabel();
        creaGiocattolo = new javax.swing.JButton();
        informations = new javax.swing.JLabel();
        istruzioni = new javax.swing.JButton();
        elfoSelezionato = new javax.swing.JLabel();
        macchinarioSelezionato = new javax.swing.JLabel();
        materialeSelezionato = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        titolo = new javax.swing.JLabel();
        selezionaMateriale = new javax.swing.JButton();
        giocattoliComboBox = new javax.swing.JComboBox<>();

        scegliElfo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        scegliElfo1.setName("scegliElfo"); // NOI18N
        scegliElfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scegliElfo1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("per il funzionamento corretto dell'industria bisogna prima di tutto scegliere l'elfo che si vuole utilizzare, poii in secondo luogo bisogna assegnare un macchinario all'elfo precendentemente scelto (dato che ogni elfo ha la sua maestria ad usare un macchinario e quindi il giocattolo verrà perfetto grazie alla magia del natale), come terzo passaggio bisogna segliere il materiale con cui vogliamo creare il giocattolo (il materiale lo si sceglie in base al macchinario, dato che ogni macchinario aggiungerà la propria magia del natale al giocattolo), in fine creiamo il giocattolo e speriamo di aver fatto le giuste scelte per creare il giocattolo perfetto e di conseguenza accontentare tutti i bambini del mondo");

        scegliElfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ruben", "augusto", "cesare", "gabriele", "pietro" }));
        scegliElfo.setName("scegliElfo"); // NOI18N
        scegliElfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scegliElfoActionPerformed(evt);
            }
        });

        scegliMacchinario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tornio", "taglia diamanti", "estrusore di ghiaccio", "fresatrice", "trita luminite" }));
        scegliMacchinario.setName("scegliElfo"); // NOI18N
        scegliMacchinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scegliMacchinarioActionPerformed(evt);
            }
        });

        assegnaElfo.setText("assegna elfo -----> alla catena");
        assegnaElfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assegnaElfoActionPerformed(evt);
            }
        });

        assegnaMacchinario.setText("assegna macchinario ----> elfo selezionato");
        assegnaMacchinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assegnaMacchinarioActionPerformed(evt);
            }
        });

        materialiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "diamante", "legno", "cemento armato", "ghiaccio", "luminite" }));
        materialiComboBox.setName("scegliElfo"); // NOI18N
        materialiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialiComboBoxActionPerformed(evt);
            }
        });

        nomeGiocattolo.setText("giocattolo richiesto <3");

        creaGiocattolo.setText("crea giocattolo");
        creaGiocattolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaGiocattoloActionPerformed(evt);
            }
        });

        informations.setToolTipText("");

        istruzioni.setText("istruzioni");
        istruzioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                istruzioniActionPerformed(evt);
            }
        });

        elfoSelezionato.setText("caratteristiche elfo selezionato");

        macchinarioSelezionato.setText("caratteristiche macchinario selezionato");

        materialeSelezionato.setText("materiale selezionato");

        jButton1.setText("evento casuale");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        titolo.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        titolo.setText("Fabbrica di giocattoli di Babbo Natale");

        selezionaMateriale.setText("assegna materiale");
        selezionaMateriale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selezionaMaterialeActionPerformed(evt);
            }
        });

        giocattoliComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "robot", "accetta", "martello", "spada", "katana" }));
        giocattoliComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giocattoliComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(selezionaMateriale, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(macchinarioSelezionato, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scegliMacchinario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assegnaMacchinario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(assegnaElfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(materialiComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scegliElfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elfoSelezionato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(informations)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(titolo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(istruzioni)
                                .addGap(71, 71, 71)
                                .addComponent(jButton1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nomeGiocattolo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                .addComponent(creaGiocattolo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(materialeSelezionato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(giocattoliComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 280, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scegliElfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assegnaElfo)
                .addGap(21, 21, 21)
                .addComponent(elfoSelezionato)
                .addGap(18, 18, 18)
                .addComponent(scegliMacchinario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assegnaMacchinario)
                .addGap(22, 22, 22)
                .addComponent(macchinarioSelezionato, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(materialiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selezionaMateriale)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(informations))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(materialeSelezionato)
                        .addGap(10, 10, 10)
                        .addComponent(giocattoliComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(creaGiocattolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeGiocattolo)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(istruzioni)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scegliElfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scegliElfoActionPerformed
        
        
    }//GEN-LAST:event_scegliElfoActionPerformed

    private void scegliElfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scegliElfo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scegliElfo1ActionPerformed

    private void scegliMacchinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scegliMacchinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scegliMacchinarioActionPerformed

    private void materialiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialiComboBoxActionPerformed

    private void istruzioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_istruzioniActionPerformed
        String testo = " per il funzionamento corretto dell'industria:" + "\n"
                  + " bisogna prima di tutto scegliere l'elfo che si vuole utilizzare,"+"\n"
                  + " poi in secondo luogo bisogna assegnare un macchinario all'elfo precendentemente scelto " +"\n"+ " (dato che ogni elfo ha la sua maestria ad usare un macchinario e quindi il giocattolo verrà perfetto grazie alla magia del natale),"+"\n"
                  + " come terzo passaggio bisogna segliere il materiale con cui vogliamo creare il giocattolo"+"\n"+" (il materiale lo si sceglie in base al macchinario, dato che ogni macchinario aggiungerà la propria magia del natale al giocattolo),"+"\n"
                  + " in fine creiamo il giocattolo"+"\n"+" e speriamo di aver fatto le giuste scelte per creare il giocattolo perfetto e di conseguenza accontentare tutti i bambini del mondo";
        JOptionPane.showMessageDialog(null, testo);
    }//GEN-LAST:event_istruzioniActionPerformed

    private void assegnaElfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assegnaElfoActionPerformed
        String tipo = Elfo.tipoElfo();
        e = new Elfo((String)scegliElfo.getSelectedItem(), tipo);
        elfoSelezionato.setText(String.valueOf(e));
    }//GEN-LAST:event_assegnaElfoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void assegnaMacchinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assegnaMacchinarioActionPerformed
        m = new Macchinario((String)scegliMacchinario.getSelectedItem());
        macchinarioSelezionato.setText(String.valueOf(m));
    }//GEN-LAST:event_assegnaMacchinarioActionPerformed

    private void selezionaMaterialeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selezionaMaterialeActionPerformed

        materialeSelezionato.setText((String)materialiComboBox.getSelectedItem());
    }//GEN-LAST:event_selezionaMaterialeActionPerformed

    private void creaGiocattoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaGiocattoloActionPerformed
        g = new Giocattolo((String)giocattoliComboBox.getSelectedItem(),(Materiale)materialiComboBox.getSelectedItem());
        nomeGiocattolo.setText(String.valueOf(g));
    }//GEN-LAST:event_creaGiocattoloActionPerformed

    private void giocattoliComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giocattoliComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giocattoliComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SalvataggioNataleInterface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assegnaElfo;
    private javax.swing.JButton assegnaMacchinario;
    private javax.swing.JButton creaGiocattolo;
    private javax.swing.JLabel elfoSelezionato;
    private javax.swing.JComboBox<String> giocattoliComboBox;
    private javax.swing.JLabel informations;
    private javax.swing.JButton istruzioni;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel macchinarioSelezionato;
    private javax.swing.JLabel materialeSelezionato;
    private javax.swing.JComboBox<String> materialiComboBox;
    private javax.swing.JLabel nomeGiocattolo;
    private javax.swing.JComboBox<String> scegliElfo;
    private javax.swing.JComboBox<String> scegliElfo1;
    private javax.swing.JComboBox<String> scegliMacchinario;
    private javax.swing.JButton selezionaMateriale;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
