/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salvataggionatale;

import java.awt.Color;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author lleshi.alessandro
 */
public class SalvataggioNataleInterface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SalvataggioNataleInterface.class.getName());
    
    Elfo e;
    Macchinario m;
    CatenaDiMontaggio c = new CatenaDiMontaggio();

    Materiale.materiali materiale;
    ArrayList <String> nomiElfi = new ArrayList();
    ArrayList <String> nomiMacchinari = new ArrayList();
    Giocattolo g;
    int i = 0;
    int j = 0;
    int k = 0;
    int contaE = 0;
    int contaM = 0;
    boolean a;
    boolean b;
    boolean z;
    boolean d;
    
    
    
    public SalvataggioNataleInterface() {
        Color h = new Color(30,140,30);
        this.getContentPane().setBackground(h);
        initComponents();
        
        
        jLabel1.setVisible(false);//primo elfo
        jLabel2.setVisible(false);//secondo elfo
        jLabel4.setVisible(false);//terzo elfo
        
        jLabel6.setVisible(false);//primo macchinario
        jLabel7.setVisible(false);//secondo macchianrio
        jLabel10.setVisible(false);//terzo macchinario
        
        startFabbrica.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scegliElfo1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        scegliElfo = new javax.swing.JComboBox<>();
        scegliMacchinario = new javax.swing.JComboBox<>();
        assegnaElfo = new javax.swing.JButton();
        assegnaMacchinario = new javax.swing.JButton();
        materialiComboBox = new javax.swing.JComboBox<>();
        nomeGiocattolo = new javax.swing.JLabel();
        creaGiocattolo = new javax.swing.JButton();
        informations = new javax.swing.JLabel();
        istruzioni = new javax.swing.JButton();
        elfoSelezionato = new javax.swing.JLabel();
        macchinarioSelezionato = new javax.swing.JLabel();
        materialeSelezionato = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        titolo = new javax.swing.JLabel();
        selezionaMateriale = new javax.swing.JButton();
        giocattoliComboBox = new javax.swing.JComboBox<>();
        startFabbrica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        punteggio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        scegliElfo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        scegliElfo1.setName("scegliElfo"); // NOI18N
        scegliElfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scegliElfo1ActionPerformed(evt);
            }
        });

        jLabel3.setText("secondo elfo");

        jLabel9.setText("terzo macchinario");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("per il funzionamento corretto dell'industria bisogna prima di tutto scegliere l'elfo che si vuole utilizzare, poii in secondo luogo bisogna assegnare un macchinario all'elfo precendentemente scelto (dato che ogni elfo ha la sua maestria ad usare un macchinario e quindi il giocattolo verrà perfetto grazie alla magia del natale), come terzo passaggio bisogna segliere il materiale con cui vogliamo creare il giocattolo (il materiale lo si sceglie in base al macchinario, dato che ogni macchinario aggiungerà la propria magia del natale al giocattolo), in fine creiamo il giocattolo e speriamo di aver fatto le giuste scelte per creare il giocattolo perfetto e di conseguenza accontentare tutti i bambini del mondo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scegliElfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "augusto", "gabriele", "pietro" }));
        scegliElfo.setName("scegliElfo"); // NOI18N
        scegliElfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scegliElfoActionPerformed(evt);
            }
        });
        getContentPane().add(scegliElfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 54, 180, 31));

        scegliMacchinario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tornio", "taglia diamanti", "estrusore di ghiaccio", "fresatrice", "trita luminite" }));
        scegliMacchinario.setName("scegliElfo"); // NOI18N
        scegliMacchinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scegliMacchinarioActionPerformed(evt);
            }
        });
        getContentPane().add(scegliMacchinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 180, 31));

        assegnaElfo.setText("assegna elfo -----> alla catena");
        assegnaElfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assegnaElfoActionPerformed(evt);
            }
        });
        getContentPane().add(assegnaElfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 91, 274, -1));

        assegnaMacchinario.setText("assegna macchinario ----> elfo selezionato");
        assegnaMacchinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assegnaMacchinarioActionPerformed(evt);
            }
        });
        getContentPane().add(assegnaMacchinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 218, 274, -1));

        materialiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "diamanti", "ghiaccio", "luminite", "legno", "cemento" }));
        materialiComboBox.setName("scegliElfo"); // NOI18N
        materialiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialiComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(materialiComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 181, 31));

        nomeGiocattolo.setText("giocattolo richiesto <3");
        getContentPane().add(nomeGiocattolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 460, 255, -1));

        creaGiocattolo.setText("crea giocattolo");
        creaGiocattolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaGiocattoloActionPerformed(evt);
            }
        });
        getContentPane().add(creaGiocattolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 431, 268, -1));

        informations.setToolTipText("");
        getContentPane().add(informations, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 475, -1, -1));

        istruzioni.setText("istruzioni");
        istruzioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                istruzioniActionPerformed(evt);
            }
        });
        getContentPane().add(istruzioni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        elfoSelezionato.setText("caratteristiche elfo selezionato");
        getContentPane().add(elfoSelezionato, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 126, 340, -1));

        macchinarioSelezionato.setText("caratteristiche macchinario selezionato");
        getContentPane().add(macchinarioSelezionato, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 340, -1));

        materialeSelezionato.setText("materiale selezionato");
        getContentPane().add(materialeSelezionato, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 180, -1));

        jButton1.setText("evento casuale");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        titolo.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        titolo.setText("Fabbrica di giocattoli di Babbo Natale");
        getContentPane().add(titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 6, -1, -1));

        selezionaMateriale.setText("assegna materiale");
        selezionaMateriale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selezionaMaterialeActionPerformed(evt);
            }
        });
        getContentPane().add(selezionaMateriale, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 274, -1));

        giocattoliComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "robot", "accetta", "martello", "spada", "katana" }));
        giocattoliComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giocattoliComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(giocattoliComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 394, 180, 31));

        startFabbrica.setText("start");
        startFabbrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startFabbricaActionPerformed(evt);
            }
        });
        getContentPane().add(startFabbrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 80, 100));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 80, 110));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 100, 140));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 150, 130));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 150, 130));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 328, 150, 150));
        getContentPane().add(punteggio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 90, 20));

        jLabel8.setText("qualità:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 60, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scegliElfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scegliElfoActionPerformed
        
        
    }//GEN-LAST:event_scegliElfoActionPerformed

    private void scegliElfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scegliElfo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scegliElfo1ActionPerformed

    private void scegliMacchinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scegliMacchinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scegliMacchinarioActionPerformed

    private void materialiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialiComboBoxActionPerformed

    private void istruzioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_istruzioniActionPerformed
        String testo = """
                        per il funzionamento corretto dell'industria:
                        bisogna prima di tutto scegliere l'elfo che si vuole utilizzare,
                        poi in secondo luogo bisogna assegnare un macchinario all'elfo precendentemente scelto 
                        (dato che ogni elfo ha la sua maestria ad usare un macchinario e quindi il giocattolo verr\u00e0 perfetto grazie alla magia del natale),
                        come terzo passaggio bisogna segliere il materiale con cui vogliamo creare il giocattolo
                        (il materiale lo si sceglie in base al macchinario, dato che ogni macchinario aggiunger\u00e0 la propria magia del natale al giocattolo),
                        in fine creiamo il giocattolo
                        e speriamo di aver fatto le giuste scelte per creare il giocattolo perfetto e di conseguenza accontentare tutti i bambini del mondo
                        CLICCA START SOLO QUANDO HAI INSERITO TUTTI I DATI""";
                        
        JOptionPane.showMessageDialog(null, testo);
    }//GEN-LAST:event_istruzioniActionPerformed

    private void assegnaElfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assegnaElfoActionPerformed
        a = true;
        if(contaE <= 3){
            if(nomiElfi.size() == 0){
                nomiElfi.add((String)scegliElfo.getSelectedItem());
                String tipo = Elfo.tipoElfo();
                e = new Elfo((String)scegliElfo.getSelectedItem(), tipo);
                elfoSelezionato.setText(String.valueOf(e));
                c.addElfi(e.getNome()); 
            }
            else{
                if(!nomiElfi.contains((String)scegliElfo.getSelectedItem())){
                String tipo = Elfo.tipoElfo();
                e = new Elfo((String)scegliElfo.getSelectedItem(), tipo);
                elfoSelezionato.setText(String.valueOf(e));
                nomiElfi.add((String)scegliElfo.getSelectedItem());
                c.addElfi(e.getNome()); 
                }
            }
            contaE++;
        }
    }//GEN-LAST:event_assegnaElfoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //da sistemare il calcolo della qualità
        
        c.events();
        
        String testo = " l 'evento che ti è capitato è: " + c.e;               
        JOptionPane.showMessageDialog(null, testo);
        
        punteggio.setText(String.valueOf(c.getQualita()));
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void assegnaMacchinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assegnaMacchinarioActionPerformed

        b = true;
        if(contaM <= 3){
            if(nomiMacchinari.size() == 0){
                nomiMacchinari.add((String)scegliMacchinario.getSelectedItem());
                m = new Macchinario((String)scegliMacchinario.getSelectedItem(), c);
                macchinarioSelezionato.setText(String.valueOf(m));
                c.addMacchinari(m.getNome()); 
            }
            else{
                if(!nomiMacchinari.contains((String)scegliMacchinario.getSelectedItem())){
                m = new Macchinario((String)scegliMacchinario.getSelectedItem(), c);
                nomiMacchinari.add((String)scegliMacchinario.getSelectedItem());
                macchinarioSelezionato.setText(String.valueOf(m));
                c.addMacchinari(m.getNome()); 
                }
            }
            contaM++;
        }
    }//GEN-LAST:event_assegnaMacchinarioActionPerformed

    private void selezionaMaterialeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selezionaMaterialeActionPerformed
        z = true;
        materialeSelezionato.setText((String)materialiComboBox.getSelectedItem());
    }//GEN-LAST:event_selezionaMaterialeActionPerformed

    private void creaGiocattoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaGiocattoloActionPerformed
        d = true;
        nomeGiocattolo.setText((String)giocattoliComboBox.getSelectedItem());
        
        if(a == true && b == true && z == true && d == true){
            startFabbrica.setEnabled(true);
        }
    }//GEN-LAST:event_creaGiocattoloActionPerformed

    private void giocattoliComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giocattoliComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giocattoliComboBoxActionPerformed

    private void startFabbricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startFabbricaActionPerformed
        creaGiocattolo.setEnabled(false);
        
        e = new ElfoMagico((String)scegliElfo.getSelectedItem(), Elfo.tipoElfo());//elfo magico
        e = new ElfoMeccanico((String)scegliElfo.getSelectedItem(), Elfo.tipoElfo());//elfo meccanico
               
        m = new Tornio("tornio",c);
        m = new Fresatrice("fresatrice",c);
        m = new TagliaDiamanti("taglia diamanti",c);
        m = new EstrusoreDiGhiaccio("estrusore di ghiaccio",c);
        m = new TritaLuminite("trita luminite",c);
        
        String s = (String)materialiComboBox.getSelectedItem();
        materiale = Materiale.materiali.valueOf(s);//materiale
        
        g = new Giocattolo((String)giocattoliComboBox.getSelectedItem(), materiale);//giocattolo
        
        //scelta elfi
        jLabel1.setVisible(true);//primo elfo
        jLabel2.setVisible(true);//secondo elfo
        jLabel4.setVisible(true);//terzo elfo
        JLabel[] JElfi = {jLabel1, jLabel2, jLabel4};
        if(i < 3){
            //devo usare c.elfi[i] per vedere se l'elfo è gia stato inserito nelle label
        for (String ee: nomiElfi){
                if(c.elfi.contains(ee)){
                    JElfi[i].setIcon(new ImageIcon((URL)getClass().getResource(c.controllaElfo(ee))));
                    e.ControllaMacchinario(m);
                    i++;
                }
            }
        
        }
        
        //scelta macchinario
        JLabel[] JMacchinari = {jLabel6, jLabel7, jLabel10};
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel10.setVisible(true);
        if(k < 3){
        for (String ee: nomiMacchinari){
                if(c.macchinari.contains(ee)){
                    JMacchinari[k].setIcon(new ImageIcon((URL)getClass().getResource(c.controllaMacchinario(ee))));
                    k++;
                }
            }
        
        }
        
        m.AumentaQualita(g, nomiMacchinari);
        
        j++;
        if(j == 3){
            punteggio.setText(String.valueOf(c.getQualita()));
        }
        
        c.elfi.clear();
        c.macchinari.clear();
    }//GEN-LAST:event_startFabbricaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SalvataggioNataleInterface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assegnaElfo;
    private javax.swing.JButton assegnaMacchinario;
    private javax.swing.JButton creaGiocattolo;
    private javax.swing.JLabel elfoSelezionato;
    private javax.swing.JComboBox<String> giocattoliComboBox;
    private javax.swing.JLabel informations;
    private javax.swing.JButton istruzioni;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel macchinarioSelezionato;
    private javax.swing.JLabel materialeSelezionato;
    private javax.swing.JComboBox<String> materialiComboBox;
    private javax.swing.JLabel nomeGiocattolo;
    private javax.swing.JLabel punteggio;
    private javax.swing.JComboBox<String> scegliElfo;
    private javax.swing.JComboBox<String> scegliElfo1;
    private javax.swing.JComboBox<String> scegliMacchinario;
    private javax.swing.JButton selezionaMateriale;
    private javax.swing.JButton startFabbrica;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
